global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:
  - job_name: "SystemSentinel"
    metrics_path: /metrics
    static_configs:
      - targets: ["app:8000"]

  - job_name: "blackbox_ssh_netbird"
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets: ["100.124.161.192:22"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  - job_name: "blackbox_duckdns_http"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets: ["https://myadguardzi.duckdns.org/"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  - job_name: "blackbox_duckdns_dns"
    metrics_path: /probe
    params:
      module: [dns_udp]
    static_configs:
      - targets: ["1.1.1.1:53"]
        labels:
          instance: "myadguardzi.duckdns.org"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [instance]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
